### ISSUE TITLE
Add a Hello-World in any programming Language you like :computer: 

### ISSUE THREAD

**Issue by iParadocx** [Codewave-Crew/Lets-Do-Code#1]
- Add your Hello-World in the language folder :file_folder: in the main branch.  
- if language folder doesn't exist you can make folder :file_folder: and add your program in it.  
- You can find new languages in this [Programming Language List](https://en.wikipedia.org/wiki/List_of_programming_languages).     
- Give star :star: to this repository.

**Comment by princekushwaha** [comment]
did you mean, I have to print "Hello World" in any language.

**Comment by dlx996** [comment]
> did you mean, I have to print "Hello World" in any language.

@princekushwaha yes. follow the instructions.

**Comment by badshahlala0102** [comment]
I have add Hello World in Python, Kindly look into that!

**Comment by AlternateWalls** [comment]
Added Hello World! in C++
