### ISSUE TITLE
Add a Hello-World in any programming Language you like :computer: 

### ISSUE THREAD

**Issue by dlx996** [Codewave-Crew/Lets-Do-Code#3]
- Add your Hello-World in the language folder :file_folder: in the main branch.  
- if language folder doesn't exist you can make folder :file_folder: and add your program in it.  
- You can find new languages in this [Programming Language List](https://en.wikipedia.org/wiki/List_of_programming_languages).

**Comment by ManishS6** [comment]
@dlx996 I would like to work on this
